# Generated by Django 5.0.6 on 2024-06-01 23:08

import users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
