# Generated by Django 5.0.6 on 2024-06-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_transaction_amount_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
